build:
	go build -o apartment-renting cmd/main.go

run:
	go run cmd/main.go

docker-build:
	docker build -t apartment-renting .

docker-run:
	docker run -it apartment-renting

docker-compose-up:
	docker-compose up
